---
abstract: "It's new $module"
author:
  - 'mix3 <himachocost333@hotmail.co.jp>'
build_requires:
  Test::More: '0.98'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v2.2.0, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: SQL-Translator-Producer-PlantUML
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  SQL::Translator::Producer::PlantUML:
    file: lib/SQL/Translator/Producer/PlantUML.pm
    version: '0.03'
requires:
  SQL::Translator: '0'
  Template: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/mix3/p5-SQL-Translator-Producer-PlantUML/issues
  homepage: https://github.com/mix3/p5-SQL-Translator-Producer-PlantUML
  repository: git://github.com/mix3/p5-SQL-Translator-Producer-PlantUML.git
version: '0.03'
x_authority: cpan:HIMACHOCO
